version: "3.7"
services:
  app:
    build:
      args:
        user: addincw
        uuid: 1996
      context: ../
      dockerfile: ./docker/Dockerfile
    image: antpress
    container_name: antpress-app
    restart: unless-stopped
    volumes:
      - ../:/var/www
    networks:
      - antpress_network
  nginx:
    image: nginx:1.17-alpine
    container_name: antpress-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ../:/var/www
      - ./conf/nginx:/etc/nginx/conf.d
    networks:
      - antpress_network
  db:
    image: mysql:5.7
    container_name: antpress-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - antpress_network
  pkgmngr:
    restart: 'no'
    image: composer:latest
    container_name: antpress-pkgmngr
    command: install --ignore-platform-reqs --no-scripts
    volumes:
      - ../:/app
networks:
  antpress_network:
    driver: bridge